export const uzRegionsDistricts = [
  {
    id: 1,
    region: "Andijon viloyati",
    districts: [
      {
        id: 16,
        name: "Oltinko'l tumani",
      },
      {
        id: 17,
        name: "Andijon tumani",
      },
      {
        id: 18,
        name: "Baliqchi tumani",
      },
      {
        id: 19,
        name: "Bo'z tumani",
      },
      {
        id: 20,
        name: "Buloqboshi tumani",
      },
      {
        id: 21,
        name: "Jalaquduq tumani",
      },
      {
        id: 22,
        name: "Izboskan tumani",
      },
      {
        id: 23,
        name: "Ulug'nor tumani",
      },
      {
        id: 24,
        name: "Qo'rg'ontepa tumani",
      },
      {
        id: 25,
        name: "Asaka tumani",
      },
      {
        id: 26,
        name: "Marxamat tumani",
      },
      {
        id: 27,
        name: "Shahrixon tumani",
      },
      {
        id: 28,
        name: "Paxtaobod tumani",
      },
      {
        id: 29,
        name: "Xo'jaobod tumani",
      },
      {
        id: 30,
        name: "Andijon",
      },
      {
        id: 31,
        name: "Xonobod",
      },
    ],
  },
  {
    id: 2,
    region: "Buxoro viloyati",
    districts: [
      {
        id: 32,
        name: "Olot tumani",
      },
      {
        id: 33,
        name: "Buxoro tumani",
      },
      {
        id: 34,
        name: "Vobkent tumani",
      },
      {
        id: 35,
        name: "G'ijduvon tumani",
      },
      {
        id: 36,
        name: "Kogon tumani",
      },
      {
        id: 37,
        name: "Qorako'l tumani",
      },
      {
        id: 38,
        name: "Qorovulbozor tumani",
      },
      {
        id: 39,
        name: "Peshku tumani",
      },
      {
        id: 40,
        name: "Romitan tumani",
      },
      {
        id: 41,
        name: "Jondor tumani",
      },
      {
        id: 42,
        name: "Shofirkon tumani",
      },
      {
        id: 43,
        name: "Buxoro",
      },
      {
        id: 44,
        name: "Kogon",
      },
    ],
  },
  {
    id: 3,
    region: "Jizzax viloyati",
    districts: [
      {
        id: 45,
        name: "Arnasoy tumani",
      },
      {
        id: 46,
        name: "Baxmal tumani",
      },
      {
        id: 47,
        name: "G'allaorol tumani",
      },
      {
        id: 49,
        name: "Do'stlik tumani",
      },
      {
        id: 50,
        name: "Zomin tumani",
      },
      {
        id: 51,
        name: "Zarbdor tumani",
      },
      {
        id: 52,
        name: "Mirzacho'l tumani",
      },
      {
        id: 53,
        name: "Zafarobod tumani",
      },
      {
        id: 54,
        name: "Paxtakor tumani",
      },
      {
        id: 55,
        name: "Forish tumani",
      },
      {
        id: 56,
        name: "Yangiobod tumani",
      },
      {
        id: 2905,
        name: "Sh.Rashidov tumani",
      },
      {
        id: 57,
        name: "Jizzax",
      },
    ],
  },
  {
    id: 4,
    region: "Qashqadaryo viloyati",
    districts: [
      { id: 58, name: "G'uzor tumani" },
      { id: 59, name: "Dehqonobod tumani" },
      { id: 60, name: "Qamashi tumani" },
      { id: 61, name: "Qarshi tumani" },
      { id: 62, name: "Koson tumani" },
      { id: 63, name: "Kitob tumani" },
      { id: 64, name: "Mirishkor tumani" },
      { id: 65, name: "Muborak tumani" },
      { id: 66, name: "Nishon tumani" },
      { id: 67, name: "Kasbi tumani" },
      { id: 68, name: "Chiroqchi tumani" },
      { id: 69, name: "Shahrisabz tumani" },
      { id: 70, name: "Yakkabog' tumani" },
      { id: 71, name: "Qarshi" },
      { id: 72, name: "Shahrisabz" },
      { id: 8591, name: "Ko‘kdala tumani" },
    ],
  },
  {
    id: 5,
    region: "Navoiy viloyati",
    districts: [
      { id: 73, name: "Konimex tumani" },
      { id: 74, name: "Qiziltepa tumani" },
      { id: 75, name: "Navbahor tumani" },
      { id: 76, name: "Karmana tumani" },
      { id: 77, name: "Nurota tumani" },
      { id: 78, name: "Tomdi tumani" },
      { id: 79, name: "Uchquduq tumani" },
      { id: 80, name: "Xatirchi tumani" },
      { id: 81, name: "Navoiy" },
      { id: 2939, name: "Zarafshon" },
      { id: 8584, name: "G‘ozg‘on tumani" },
    ],
  },
  {
    id: 6,
    region: "Namangan viloyati",
    districts: [
      { id: 83, name: "Mingbuloq tumani" },
      { id: 84, name: "Kosonsoy tumani" },
      { id: 85, name: "Namangan tumani" },
      { id: 86, name: "Norin tumani" },
      { id: 87, name: "Pop tumani" },
      { id: 88, name: "To'raqo'rg'on tumani" },
      { id: 89, name: "Uychi tumani" },
      { id: 90, name: "Uchqo'rg'on tumani" },
      { id: 91, name: "Chortoq tumani" },
      { id: 92, name: "Chust tumani" },
      { id: 93, name: "Yangiqo'rg'on tumani" },
      { id: 94, name: "Namangan" },
      { id: 8595, name: "Davlatobod tumani" },
      { id: 8601, name: "Yangi Namangan tumani" },
    ],
  },
  {
    id: 7,
    region: "Samarqand viloyati",
    districts: [
      { id: 95, name: "Oqdaryo tumani" },
      { id: 96, name: "Bulung'ur tumani" },
      { id: 97, name: "Jomboy tumani" },
      { id: 98, name: "Ishtixon tumani" },
      { id: 99, name: "Kattaqo'rg'on tumani" },
      { id: 100, name: "Qo'shrabot tumani" },
      { id: 101, name: "Narpay tumani" },
      { id: 102, name: "Payariq tumani" },
      { id: 103, name: "Pastdarg'om tumani" },
      { id: 104, name: "Paxtachi tumani" },
      { id: 105, name: "Samarqand tumani" },
      { id: 106, name: "Nurobod tumani" },
      { id: 107, name: "Urgut tumani" },
      { id: 108, name: "Tayloq tumani" },
      { id: 109, name: "Samarqand" },
      { id: 110, name: "Kattaqo'rg'on" },
    ],
  },
  {
    id: 8,
    region: "Sirdaryo viloyati",
    districts: [
      { id: 125, name: "Oqoltin tumani" },
      { id: 126, name: "Boyovut tumani" },
      { id: 127, name: "Sayxunobod tumani" },
      { id: 128, name: "Guliston tumani" },
      { id: 129, name: "Sardoba tumani" },
      { id: 130, name: "Mirzaobod tumani" },
      { id: 131, name: "Sirdaryo tumani" },
      { id: 132, name: "Xovos tumani" },
      { id: 133, name: "Guliston" },
      { id: 134, name: "Shirin" },
      { id: 135, name: "Yangiyer" },
      { id: 8574, name: "Baxt shaxar" },
    ],
  },
  {
    id: 9,
    region: "Toshkent shahri",
    districts: [
      { id: 137, name: "Uchtepa tumani" },
      { id: 138, name: "Bektemir tumani" },
      { id: 139, name: "Yunusobod tumani" },
      { id: 140, name: "Mirzo Ulug'bek tumani" },
      { id: 141, name: "Mirobod tumani" },
      { id: 142, name: "Shayxontohur tumani" },
      { id: 143, name: "Olmazor tumani" },
      { id: 144, name: "Sirg'ali tumani" },
      { id: 145, name: "Yakkasaroy tumani" },
      { id: 146, name: "Yashnobod tumani" },
      { id: 147, name: "Chilonzor tumani" },
      { id: 1487, name: "Yangihayot tumani" },
    ],
  },
  {
    id: 10,
    region: "Toshkent viloyati",
    districts: [
      { id: 148, name: "Oqqo'rg'on tumani" },
      { id: 149, name: "Ohangaron tumani" },
      { id: 150, name: "Bekobod tumani" },
      { id: 151, name: "Bo'stonliq tumani" },
      { id: 152, name: "Bo'ka tumani" },
      { id: 154, name: "Zangiota tumani" },
      { id: 155, name: "Yuqorichirchiq tumani" },
      { id: 156, name: "Qibray tumani" },
      { id: 157, name: "Parkent tumani" },
      { id: 158, name: "Piskent tumani" },
      { id: 159, name: "O'rtachirchiq tumani" },
      { id: 160, name: "Chinoz tumani" },
      { id: 161, name: "Yangiyo'l tumani" },
      { id: 162, name: "Toshkent tumani" },
      { id: 163, name: "Nurafshon" },
      { id: 164, name: "Olmaliq" },
      { id: 165, name: "Angren" },
      { id: 166, name: "Bekobod" },
      { id: 167, name: "Ohangaron" },
      { id: 168, name: "Chirchiq" },
      { id: 169, name: "Yangiyo'l" },
      { id: 5867, name: "Quyichirchiq tumani" },
    ],
  },
  {
    id: 11,
    region: "Farg'ona viloyati",
    districts: [
      { id: 170, name: "Oltiariq tumani" },
      { id: 171, name: "Qo'shtepa tumani" },
      { id: 172, name: "Bog'dod tumani" },
      { id: 173, name: "Buvayda tumani" },
      { id: 174, name: "Beshariq tumani" },
      { id: 175, name: "Quva tumani" },
      { id: 176, name: "Uchko'prik tumani" },
      { id: 177, name: "Rishton tumani" },
      { id: 178, name: "So'x tumani" },
      { id: 179, name: "Toshloq tumani" },
      { id: 180, name: "O'zbekiston tumani" },
      { id: 181, name: "Farg'ona tumani" },
      { id: 182, name: "Dang'ara tumani" },
      { id: 183, name: "Furqat tumani" },
      { id: 184, name: "Yozyovon tumani" },
      { id: 185, name: "Farg'ona" },
      { id: 186, name: "Qo'qon" },
      { id: 187, name: "Quvasoy" },
      { id: 188, name: "Marg'ilon" },
    ],
  },
  {
    id: 12,
    region: "Xorazm viloyati",
    districts: [
      { id: 189, name: "Bog'ot tumani" },
      { id: 190, name: "Gurlan tumani" },
      { id: 191, name: "Qo'shko'pir tumani" },
      { id: 192, name: "Urganch tumani" },
      { id: 193, name: "Xazorasp tumani" },
      { id: 194, name: "Xonqa tumani" },
      { id: 195, name: "Xiva tumani" },
      { id: 196, name: "Shovot tumani" },
      { id: 197, name: "Yangiariq tumani" },
      { id: 198, name: "Yangibozor tumani" },
      { id: 199, name: "Urganch" },
      { id: 200, name: "Xiva" },
      { id: 8581, name: "Tuproqqal’a tumani" },
    ],
  },
  {
    id: 13,
    region: "Qoraqalpog'iston Respublikasi",
    districts: [
      { id: 201, name: "Amudaryo tumani" },
      { id: 202, name: "Beruniy tumani" },
      { id: 203, name: "Qorao'zak tumani" },
      { id: 204, name: "Kegeyli tumani" },
      { id: 205, name: "Qo'ng'irot tumani" },
      { id: 206, name: "Qanliko'l tumani" },
      { id: 207, name: "Mo'ynoq tumani" },
      { id: 208, name: "Nukus tumani" },
      { id: 209, name: "Taxiatosh tumani" },
      { id: 210, name: "Taxtako'pir tumani" },
      { id: 211, name: "To'rtko'l tumani" },
      { id: 212, name: "Xo'jayli tumani" },
      { id: 213, name: "Chimboy tumani" },
      { id: 214, name: "Shumanay tumani" },
      { id: 215, name: "Ellikqal'a tumani" },
      { id: 216, name: "Nukus" },
      { id: 8575, name: "Bo‘zatov tumani" },
    ],
  },
  {
    id: 14,
    region: "Surxondaryo viloyati",
    districts: [
      { id: 111, name: "Oltinsoy tumani" },
      { id: 112, name: "Angor tumani" },
      { id: 113, name: "Boysun tumani" },
      { id: 114, name: "Muzrabot tumani" },
      { id: 115, name: "Denov tumani" },
      { id: 116, name: "Jarqo'rg'on tumani" },
      { id: 117, name: "Qumqo'rg'on tumani" },
      { id: 118, name: "Qiziriq tumani" },
      { id: 119, name: "Sariosiyo tumani" },
      { id: 120, name: "Termiz tumani" },
      { id: 121, name: "Uzun tumani" },
      { id: 122, name: "Sherobod tumani" },
      { id: 123, name: "Sho'rchi tumani" },
      { id: 2981, name: "Termiz" },
      { id: 8580, name: "Bandixon tumani" },
    ],
  },
];
